### ISSUE TITLE
It's not launching at all

### ISSUE THREAD

**Issue by gkeornjsha** [jrbudda/Vivecraft_111#11]
[14:27:40] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[14:27:40] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[14:27:40] [main/INFO]: Loading tweak class name com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
[14:27:40] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine URL: file:/C:/Users/HDKuser/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.11_HD_U_B2/OptiFine-1.11_HD_U_B2.jar
OptiFine ZIP file: C:\Users\HDKuser\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.11_HD_U_B2\OptiFine-1.11_HD_U_B2.jar
[14:27:40] [main/INFO]: Calling tweak class com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
MinecriftForgeTweaker: acceptOptions
MinecriftForgeTweaker: injectIntoClassLoader
Minecrift ClassTransformer
Minecrift URL: file:/C:/Users/HDKuser/AppData/Roaming/.minecraft/libraries/com/mtbs3d/minecrift/1.11-jrbudda-3/minecrift-1.11-jrbudda-3.jar
Minecrift ZIP file: java.util.zip.ZipFile@6e6619b
OptiFineTweaker: getLaunchArguments
MinecriftForgeTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[14:27:40] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_45]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_45]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more

**Comment by jrbudda** [comment]
3rd party launcher?
