### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by zonfar** [jrbudda/Vivecraft_111#12]
I used to be able to load vivecraft just fine, however now I can't load it at all, i'm not sure what happened. I tried reverting my Java 8 to Java 7 as I've seen some people have issues with latest java in general. However I am able to load minecraft normally. I can't load vivecraft on 1st or 3rd party launchers. I'm running a gtx970 and updated my drivers as well. Here is the error:

[10:56:36] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[10:56:36] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[10:56:36] [main/INFO]: Loading tweak class name com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
[10:56:36] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine URL: file:/C:/Users/MooCakes%20Beef/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.11_HD_U_B2/OptiFine-1.11_HD_U_B2.jar
OptiFine ZIP file: C:\Users\MooCakes Beef\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.11_HD_U_B2\OptiFine-1.11_HD_U_B2.jar
[10:56:36] [main/INFO]: Calling tweak class com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
MinecriftForgeTweaker: acceptOptions
MinecriftForgeTweaker: injectIntoClassLoader
Minecrift ClassTransformer
Minecrift URL: file:/C:/Users/MooCakes%20Beef/AppData/Roaming/.minecraft/libraries/com/mtbs3d/minecrift/1.11-jrbudda-3/minecrift-1.11-jrbudda-3.jar
Minecrift ZIP file: java.util.zip.ZipFile@357a56a7
OptiFineTweaker: getLaunchArguments
MinecriftForgeTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[10:56:36] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more

**Comment by jrbudda** [comment]
It's missing the main game, are you using the mojang launcher?

**Comment by zonfar** [comment]
Yeah I'm trying using both mojang launcher and 3rd party launchers, weird its missing the main game since it launches when I don't choose the vivecraft profile

**Comment by Fonzee9** [comment]
Same problem please fix

**Comment by jrbudda** [comment]
I don't think I can fix this, it works for me on my computer, there is something wrong with your computer where it can't download the game from the internet.

**Comment by zonfar** [comment]
Any idea why the game can be loaded regularly but not vive craft?

**Comment by jrbudda** [comment]
Nope. pastebin your launcher log tab.

**Comment by Fonzee9** [comment]
http://pastebin.com/AmWVQ9UW

**Comment by jrbudda** [comment]
that's game output tab, other tab please. Launcher.
