### ISSUE TITLE
NullPointerException when Initializing Game

### ISSUE THREAD

**Issue by featuredepix** [jrbudda/Vivecraft_111#20]
I've just installed the latest version for 1.11.2 (that was released a couple of days ago), but whenever I start the game I get this error straight away:

`java.lang.NullPointerException: Initializing game
	at com.mtbs3d.minecrift.provider.MCOpenVR.getPlayAreaSize(MCOpenVR.java:2121)
	at com.mtbs3d.minecrift.provider.MCOpenVR.onGuiScreenChanged(MCOpenVR.java:2163)
	at com.mtbs3d.minecrift.provider.OpenVRStereoRenderer.onGuiScreenChanged(OpenVRStereoRenderer.java:202)
	at bes.a(Minecraft.java:1246)
	at bes.an(Minecraft.java:812)
	at bes.a(Minecraft.java:629)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by jrbudda** [comment]
Its steamvr being annoying, mine's been pretty flaky lately too. Try it with steamvr already running and tracking.

**Comment by Techjar** [comment]
This was something to do with riftcat.
