### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by The-Filthy-Rotter** [jrbudda/Vivecraft_111#26]
Immediately after installation, using Nvidia driver version 376.33. Having Steam VR open or closed does nothing. 1.7.10-R2b-Vive-forge-nohydra crashes as well but with a wildly different error.

Output:
```
[23:39:50] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[23:39:50] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[23:39:50] [main/INFO]: Loading tweak class name com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
[23:39:50] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```

**Comment by jrbudda** [comment]
looks like the vivecraft library isnt being installed properly, could you try a clean install?
