### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by tambeh** [jrbudda/Vivecraft_111#35]
Hi, I've tried other versions they all worked fine except for 1.11 v1, v2, v3

[00:41:21] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by tambeh** [comment]
one thing i noticed, all the 1.11 jar files are only 1kb.

vivecraft-1.11-jrbudda-3r2.jar 1kb

but for vivecraft-1.11.2-jrbudda-7r1.jar
it's 8,983kb

**Comment by jrbudda** [comment]
are you using the actual minecraft launcher?

**Comment by tambeh** [comment]
Yeah, I'm using the launcher from their website. After I installed vivecraft (I tried 1.11 & 1.11.2), I compare both the .Jar file. 

I am able to double click the .Jar file  of 1.11.2 but when I double click the .Jar file of 1.11 (v1, v2, v3), it says it's corrupted. The jar file is always 1kb after I install the 1.11

Tried reinstalling lots of times but no luck. Also updated my java.

**Comment by jrbudda** [comment]
Is there a reason you want to use the old versions? whats happening is the launcher is failing to download the normal game jar for some reason, firewall or blocked or something.

**Comment by tambeh** [comment]
My friend is running a bukkit server and there are there are alot of plugins he wanted to keep retain. So he wouldn't want to update. But since the download file doesn't haven't problem, I guess it's a problem on my side then. Will try with turning off firewall and stuff see how it goes. Thanks!

**Comment by jrbudda** [comment]
the 1.11.2 spigot server is compatible with plugins made for 1.11
