### ISSUE TITLE
Crashes/freezes when accessing crafting table

### ISSUE THREAD

**Issue by Devilsbane99** [jrbudda/Vivecraft_111#54]
Just got the mod (love it) but when I access a crafting table, the game freezes. Anyone else with this issue?

**Comment by jrbudda** [comment]
this is with 10pre2 no forge?

**Comment by Techjar** [comment]
Does it just hang or does it crash? Logs and/or crash report would be helpful.

**Comment by Devilsbane99** [comment]
I apologize for the lack of a log. Going to post it in a few hours.
This is on 1.11. It hangs, waited 5 minutes and then I force quit, that's when it notified me it crashed

**Comment by Devilsbane99** [comment]
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException

All that shows at the end. 10 pre version for sure however


[05:04:22] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[05:04:22] [Client thread/INFO]: [STDERR]: 	at com.mtbs3d.minecrift.provider.MCOpenVR.processGui(MCOpenVR.java:832)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at com.mtbs3d.minecrift.provider.MCOpenVR.poll(MCOpenVR.java:692)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at bes.av(Minecraft.java:1565)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at bes.a(Minecraft.java:674)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:121)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[05:04:22] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[05:04:22] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException

**Comment by jrbudda** [comment]
could you pastebin the whole log, please?

**Comment by Devilsbane99** [comment]
I'm sorry sir, allow me to do so when I get back home. Tried to but it stated it was too big . Used the recent log file as reference. Thank you for responding so fast!

**Comment by jrbudda** [comment]
if you click the table and immediately force quit the log should be much smaller.

**Comment by jrbudda** [comment]
Are you playing seated or standing and what HUD options do you use? Does changing any of the above make a difference?

**Comment by Devilsbane99** [comment]
Standing. Default options. Didn't make any changes to the system. Just installed and tried to play.

**Comment by Devilsbane99** [comment]
found that I can exit using the left pad's menu button. no hard freeze

**Comment by jrbudda** [comment]
yea that is closing the gui, can you try changing the HUD placement option to see if it makes a difference?

**Comment by jrbudda** [comment]
[vivecraft-1.11.2-jrbudda-10pre3-installer.exe.zip](https://github.com/jrbudda/Vivecraft_111/files/1030569/vivecraft-1.11.2-jrbudda-10pre3-installer.exe.zip)
also try with this version and lets make sure i didnt inadvertantly fix whatever issue youre having.

**Comment by Devilsbane99** [comment]
Okay, giving it the ol college try. sec

**Comment by Devilsbane99** [comment]
It WORKS!!!
Not even a slight of lag!

**Comment by jrbudda** [comment]
well that explains it lol, you musta grabbed a 10pre version with a bug in it

**Comment by Devilsbane99** [comment]
Whaaa! I was so "careful"! Lol. smh, picked the latest one I could find. Sorry for being a noob and THANK YOU for being so proactive in helping a scrub.
